import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { StatementProvider } from "@/context/StatementContext";
import Sidebar from "../core/components/Sidebar";
import Header from "@/core/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-bb-emerald ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StatementProvider>
          <header className="mb-8">
            <Header />
          </header>
          <div className="flex flex-col md:grid md:grid-cols-12 gap-6 p-4">
            <aside className="col-span-full md:col-span-2">
              <Sidebar />
            </aside>
            <main className="col-span-full md:col-span-10">{children}</main>
          </div>
        </StatementProvider>
      </body>
    </html>
  );
}
